using System.Text.Json;
using LeetCode.Scaffoldings;
using NUnit.Framework;

namespace LeetCode
{
    // https://leetcode.com/problems/delete-node-in-a-linked-list/
    public class _0237
    {
        public void DeleteNode(ListNode node)
        {
            // The most difficult part of this kata
            // was adjusting my autogenerated tests :D
            // Quite fun

            var next = node.next;
            node.val = next.val;
            node.next = next.next;
        }

        [Test]
        [TestCase("[4,5,1,9]", 5, "[4,1,9]")]
        [TestCase("[4,5,1,9]", 1, "[4,5,9]")]
        public void Test(string rawHead, int nodeValue, string rawExpected)
        {
            var head = ListNode.FromString(rawHead);
            var expected = ListNode.FromString(rawExpected);

            ListNode node = default!;
            var next = head.next;
            while (next is not null)
            {
                if (nodeValue == next.val)
                {
                    node = next;
                    break;
                }

                next = next.next;
            }

            DeleteNode(node);

            Assert.That(head, Is.EqualTo(expected));
        }
    }
}
